### ISSUE TITLE
Use New Tab

### ISSUE THREAD

**Issue by orschiro** [joeyespo/inbox-by-gmail-checker#8] opened 2016-01-15 06:30 UTC
Hi @joeyespo,

Just a quick idea:

Could the checker identify an existing open tab and rather open inbox in this tab on click of the checker's icon?

Currently, if there is an open new tab, the checker still does open Inbox in another new tab rather the already opened new tab. 

Thankfully,

~Robert

**Comment by joeyespo** [comment] 2016-01-15 19:58
Hmm, it should already do this. Is your Inbox tab on another window? #4 should have fixed that case.

**Comment by orschiro** [comment] 2016-01-16 09:51
Hey @joeyespo,

No, it's in the same window. 

Let me show you the problem in the following screencast:

[vokoscreen-2016-01-16_10-49-20.mkv](https://files.zenhub.io/569a129b6387ff8d1f046f3d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by joeyespo** [comment] 2016-01-16 14:22
Oh, my mistake! I mis-read what you wrote.

Do any other extensions do this? (I know Chrome's built-in commands do re-use the new tab page.) I don't think there's a "correct" answer here, and I personally prefer the existing behavior, so let's look to see what the rest of the extension community does and do that.

**Comment by orschiro** [comment] 2016-01-17 06:01
@joeyespo,

Indeed I'm using a 3rd-party extension called [Keep One Pinned Tab](https://chrome.google.com/webstore/detail/keep-one-pinned-tab/nmcefdbkkkjndgafnlaikloffhdeknod) which is quite useful to always have one New Tab opened. 

It would be great if I could make it somehow compatible with the Inbox Checker. 

Any ideas?

**Comment by theborg3of5** [comment] 2016-01-21 17:46
Hey, developer of Keep One Pinned Tab here.

@joeyespo, do you know how you check whether there's already a new tab for you to use when the button is clicked? It looks like there's a custom new tab page, so if you're checking for chrome://newtab/ or similar, you might be missing it that way.

**Comment by joeyespo** [comment] 2016-01-21 18:40
@orschiro Sorry, what I meant to ask was "do any other 3rd-party extensions re-use an open New Tab" like what you're requesting? I've only seen builtin commands like History, Settings, and Extensions do this, but no extensions I've come across yet.

@theborg3of5 Wow, thanks for chiming in! I appreciate it. Yeah, I was aware of how to do this. This extension opens Inbox in its own tab (regardless of whether an existing "New Tab" is present) by design. This matches the behavior of the [Gmail Checker](https://chrome.google.com/webstore/detail/google-mail-checker/mihcahmgecmbnbcchbopgniflfhgnkff), which was the inspiration for this project.

**Comment by orschiro** [comment] 2016-01-22 11:30
@joeyespo 

> @orschiro Sorry, what I meant to ask was "do any other 3rd-party extensions re-use an open New Tab" like what you're requesting? I've only seen builtin commands like History, Settings, and Extensions do this, but no extensions I've come across yet.

I will try to find extension that does that, i.e. opening a site in the currently opened new tab. 

@theborg3of5 indeed thank you so much for trying to help out!

Just to let you both know that the issue is totally unrelated to having both extensions installed. I guess it's just that opening sites in another new tab might be a default Chrome behaviour. What do you think?

~Robert

**Comment by joeyespo** [comment] 2016-01-22 18:24
> I guess it's just that opening sites in another new tab might be a default Chrome behaviour

I believe it is. Some examples: opening a bookmark from your desktop, clicking on a link from another application, programmatically (`import webbrowser; webbrowser.open('http://example.com/')` in Python for example), etc.

> I will try to find extension that does that, i.e. opening a site in the currently opened new tab.

Sounds good. I'm going to close this for now.

Thanks for sharing your idea!

**Closed as completed by joeyespo** 2016-01-22 18:24 UTC

**Comment by orschiro** [comment] 2016-01-23 12:35
Just to let you know, [Close Extra New Tab](https://chrome.google.com/webstore/detail/close-extra-new-tabs/gkaaknlhljkigoogfhaknojpmjnlmcod/related) solves our problem! :)

-Robert

**Comment by joeyespo** [comment] 2016-01-23 14:16
@orschiro Awesome! Thanks for sharing :smiley:

**Comment by orschiro** [comment] 2016-01-23 15:08
@joeyespo you're very welcome! :)
